### ISSUE TITLE
New feature needed: open the processing job instance for the stepfunction setup

### ISSUE THREAD

**Issue by Nina0518** [Ewen2015/BatCat#5]
Hi Ewen,

Could you please add instance type as variable for new stepfunction setup? Now it's always the large instance for processing. 

Appreciate! 

Nina

**Comment by Ewen2015** [comment]
The issue has been resolved by updating to the latest version -- `batcat==0.2.49`. Thank you for reporting the issue and please let us know if you encounter any further problems.
