### ISSUE TITLE
Version change request

### ISSUE THREAD

**Issue by Nina0518** [Ewen2015/BatCat#8]
Hi Ewen,

Thank you for your fast response. Could you please help to change the version of Stepfunctions to newer one? The old one has issues and can't setup network config effectively. 
If you don't mind, you could try the dependent package versions I tested, shown as below:
  'boto3==1.34.26',
  'sagemaker==2.204.0', 
  'stepfunctions==2.3.0',

And delete the botocore, since the boto3 will include it.

Best Regards,
Nina

**Comment by Ewen2015** [comment]
Solved with updated version `batcat==0.2.50`.
